# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
  include Hyrax::ActiveEncode::FileSetBehavior
  include ::Hyrax::FileSetBehavior
  self.indexer = Hyrax::ActiveEncode::ActiveEncodeIndexer
end
